### ISSUE TITLE
Determine country from SIM

### ISSUE THREAD

**Issue by vanyasem** [hendraanggrian/countrypicker#3]
It would be nice if countrypicker could determine the country by the SIM card

Similarly to how it's done with [mukeshsolanki/country-picker-android](https://github.com/mukeshsolanki/country-picker-android):
```
val countryPicker = CountryPicker.Builder().with(this).build()
val country = countryPicker.countryFromSIM
```

Implementation: https://github.com/mukeshsolanki/country-picker-android/blob/master/countrypicker/src/main/java/com/mukesh/countrypicker/CountryPicker.java#L545

**Comment by hendraanggrian** [comment]
I thought about this, but don't know where should default country picking works UI-wise. When I have free time I will display this default option as ListView header.
